# Security Patch — STORAGE-001
# Generated by security-auditor on 2026-05-06
# Risk: HIGH
# Resource: devopsplatformacr (Storage Account)
#
# ⚠️  This patch was generated automatically.
#     Review carefully before applying.
#     DO NOT apply without stakeholder sign-off.
#
# Rollback plan:
# To undo this change, update the Terraform configuration to set `allow_blob_public_access` back to its original value (which is `true` based on the security finding) and apply it. You can do this by commenting out the line added to the above configuration. Then, run the Terraform apply command with the `-target` flag to ensure that only the `azurerm_storage_account` resource is changed.

```hcl
resource "azurerm_storage_account" "devopsplatformacr" {
  name                = "devopsplatformacr"
  resource_group_name = "your-resource-group-name"
  # Add the following line to set allow_blob_public_access to false
  allow_blob_public_access = false
}
```

# To apply (after approval):
# ```bash
terraform apply -target=module.your-module-name.azurerm_storage_account.devopsplatformacr
```

Replace `your-module-name` and `your-resource-group-name` with the actual values in your Terraform configuration.
