# Security Patch — AKS-001
# Generated by security-auditor on 2026-05-06
# Risk: HIGH
# Resource: devops-platform-aks (AKS Cluster)
#
# ⚠️  This patch was generated automatically.
#     Review carefully before applying.
#     DO NOT apply without stakeholder sign-off.
#
# Rollback plan:
# 1. Use `terraform state` to view the changed resource ID. Use the ID to identify the resource in the Azure portal.
2. In the Azure portal, navigate to the Networking section of your Kubernetes cluster.
3. Update the network rule set by enabling allow rules for your existing public IP ranges or subnets and disabling the rule that restricts access to only your specified IP range.
4. Save the changes to the network rule set.

```hcl
resource "azurerm_kubernetes_cluster" "devops-platform-aks" {
  // ...
  network_profile {
    network_policy {
      enabled = true
    }
  }
  // ...
  identity {
    // Update the identity type to SystemAssigned and assign a network rule to restrict API server access
    type = "SystemAssigned"
    network_rule_set {
      default_action = "Deny"
      rules = [
        {
          protocol         = "Https"
          source_address_prefixes = ["Your IP Range/your-subnet"] // replace with your desired IP or subnet
        },
        // Remove public IP access from default rules
        {
          protocol         = "*"
          source_address_prefixes = ["*"]
          destination_addresses = ["*"]
          actions = ["Deny"]
        },
      ]
    }
  }
}
```

# To apply (after approval):
# ```bash
terraform apply -target=azurerm_kubernetes_cluster.devops-platform-aks
```
