# Security Patch — STORAGE-003
# Generated by security-auditor on 2026-05-06
# Risk: MEDIUM
# Resource: tfstateprachi7 (Storage Account)
#
# ⚠️  This patch was generated automatically.
#     Review carefully before applying.
#     DO NOT apply without stakeholder sign-off.
#
# Rollback plan:
# To undo this change, navigate to the "Azure Active Directory" > "App registrations" section in the Azure portal, delete the service principle that was created automatically when enabling Azure AD authentication for the storage account. Then, update the Terraform configuration to restore the `allow_shared_access_key` attribute to its original value, and finally apply the changes.

```hcl
resource "azurerm_storage_account" "tfstateprachi7" {
  ...
  allow_shared_access_key  = false

  identity {
    type = "SystemAssigned"
  }
  ...
}
```

# To apply (after approval):
# ```bash
terraform apply -target azurerm_storage_account.tfstateprachi7
```
