# Security Patch — GEN-001
# Generated by security-auditor on 2026-05-06
# Risk: LOW
# Resource: audit-test-empty-rg (Resource Group)
#
# ⚠️  This patch was generated automatically.
#     Review carefully before applying.
#     DO NOT apply without stakeholder sign-off.
#
# Rollback plan:
# To undo this change, simply update the Terraform configuration to remove the newly added tags without the `-target` option, then run `terraform apply`. This will remove the tags on the resource group, reverting it to its original state.

```hcl
resource "azurerm_resource_group" "audit-test-empty-rg" {
  ...
  tags = {
    owner = "Your Name"
    environment = "Your Environment"
    stakeholders = "Your Stakeholders"
  }
}
```

# To apply (after approval):
# ```bash
terraform apply -target azurerm_resource_group.audit-test-empty-rg
```
