# Security Patch — KV-002
# Generated by security-auditor on 2026-05-06
# Risk: MEDIUM
# Resource: devops-kv (Key Vault)
#
# ⚠️  This patch was generated automatically.
#     Review carefully before applying.
#     DO NOT apply without stakeholder sign-off.
#
# Rollback plan:
# To undo this change, update the `network_acls` block to its original state:
- Set `default_action` back to `"Allow"`.
- Remove the `ip_rules` attribute or reset it to its original value, if present.

```hcl
resource "azurerm_key_vault" "devops-kv" {
  // Existing resource attributes...

  network_acls {
    default_action = "Deny"
    ip_rules       = ["${azurerm_virtual_network.devops-network.id}/32"]
  }
}
```

# To apply (after approval):
# ```bash
terraform apply -target azurerm_key_vault.devops-kv
```
